config/routes.rb
Rails.application.routes.draw do
  get "categories/index"
  get "categories/show"
  get "movie_categories/index"
  get "actor_categories/index"
  root "categories#index"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users, only: [:new, :create]
  resources :categories, only: [:index, :show]
  resources :actor_categories, only: [:index]
  resources :movie_categories, only: [:index]
  resources :actor_category_users, only: [:create]
  resources :movie_category_users, only: [:create]
end

app/models/actor.rb
class Actor < ApplicationRecord
  has_many :actor_categories
end

app/models/actor_category.rb
class ActorCategory < ApplicationRecord
  belongs_to :actor
  belongs_to :category
  has_many :actor_category_users
end

app/models/actor_category_user.rb
class ActorCategoryUser < ApplicationRecord
  belongs_to :user
  belongs_to :actor_category
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :actor_categories
  has_many :movie_categories
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :movie_categories
end

app/models/movie_category.rb
class MovieCategory < ApplicationRecord
  belongs_to :movie
  belongs_to :category
  has_many :movie_category_users
end

app/models/movie_category_user.rb
class MovieCategoryUser < ApplicationRecord
  belongs_to :user
  belongs_to :movie_category
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: {minimum: 10}, if: :password_required?

  has_many :actor_category_users
  has_many :movie_category_users

  private

  def password_required?
    password_digest.blank? || password.present?
  end
end

app/controllers/actor_categories_controller.rb
class ActorCategoriesController < ApplicationController
  before_action :require_login
  def index
    @actor_categories = ActorCategory.where(year: 2025).includes(:actor, :category)
  end
end

app/controllers/actor_category_users_controller.rb
class ActorCategoryUsersController < ApplicationController
  before_action :require_login
  def create
    @acu = ActorCategoryUser.new(actor_category_user_params)
    @acu.user = current_user
    if @acu.save
      redirect_to category_path(@acu.actor_category.category), notice: "Vote recorded!"
    else
      redirect_to category_path(@acu.actor_category.category), alert: "Vote failed."
    end
  end

  private

  def actor_category_user_params
    params.require(:actor_category_user).permit(:actor_category_id, :vote)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def require_login
    unless current_user
      redirect_to login_path, alert: "Please log in!"
    end
  end

  def require_admin
    redirect_to root_path, alert: "Admins only!" unless current_user&.admin
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_login
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @actor_nominations = @category.actor_categories.where(year: 2025).includes(:actor)
    @movie_nominations = @category.movie_categories.where(year: 2025).includes(:movie)
  end
end

app/controllers/movie_categories_controller.rb
class MovieCategoriesController < ApplicationController
  before_action :require_login
  def index
    @movie_categories = MovieCategory.where(year: 2025).includes(:movie, :category)
  end
end

app/controllers/movie_category_users_controller.rb
class MovieCategoryUsersController < ApplicationController
  before_action :require_login
  def create
    @mcu = MovieCategoryUser.new(actor_category_user_params)
    @mcu.user = current_user
    if @mcu.save
      redirect_to category_path(@mcu.movie_category.category), notice: "Vote recorded!"
    else
      redirect_to category_path(@mcu.actor_category.category), alert: "Vote failed."
    end
  end

  private

  def actor_category_user_params
    params.require(:actor_category_user).permit(:actor_category_id, :vote)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Logged in successfully!"
    else
      flash.now[:alert] = "Invalid email or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Signed up successfully!"
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :first_name, :last_name)
  end
end

app/helpers/actor_categories_helper.rb
module ActorCategoriesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/movie_categories_helper.rb
module MovieCategoriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/actor_categories/index.html.erb
<h1>ActorCategories#index</h1>
<p>Find me in app/views/actor_categories/index.html.erb</p>

app/views/categories/index.html.erb
<h1>Oscar 2025 Categories</h1>
<% @categories.each do |category| %>
  <%= link_to category.name, category_path(category) %> <br>
<% end %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<h2>Actor Nominations</h2>
<ul>
  <% @actor_nominations.each do |nom| %>
    <li><%= nom.actor.name %> - <%= form_with model: ActorCategoryUser.new, url: actor_category_users_path do |f| %>
        <%= f.hidden_field :actor_category_id, value: nom.id %>
        <%= f.number_field :vote, min: 0, max: 10 %> <%= f.submit "Vote" %>
      <% end %></li>
  <% end %>
</ul>
<h2>Movie Nominations</h2>
<ul>
  <% @movie_nominations.each do |nom| %>
    <li><%= nom.movie.title %> - <%= form_with model: MovieCategoryUser.new, url: movie_category_users_path do |f| %>
        <%= f.hidden_field :movie_category_id, value: nom.id %>
        <%= f.number_field :vote, min: 0, max: 10 %> <%= f.submit "Vote" %>
      <% end %></li>
  <% end %>
</ul>

app/views/movie_categories/index.html.erb
<h1>MovieCategories#index</h1>
<p>Find me in app/views/movie_categories/index.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_with model: @user, url: users_path do |form| %>
  <div>
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :admin, "Admin (check for admin access)" %>
    <%= form.check_box :admin %>
  </div>
  <div>
    <%= form.submit "Sign Up" %>
  </div>
<% end %>
<%= link_to "Log In", new_login_path %>